language: python
sudo: false
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36,codecov
install:
- pip install -U pip tox
script:
- tox
deploy:
  provider: pypi
  user: cfhamlet
  password:
    secure: 
  true:
    tags: true
    condition: ${TRAVIS_PYTHON_VERSION} == 3.6
